# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71af8de5effca6b1b4b908c37d05a454ea29c0e02644ad945d01b4b7d17f3fbe3ea317a03ac070e0ddc5045bee32132304f5768f26c575f376ebb6a69775428c

test:
  secret_key_base: 556a8392c2e7575a89f6184b4949e4bac4d10e233ef1d98453ee2a77a6621804a4c692c14ce6b20ab1d8f598643eecf27d90a5befcc4761cb9ba5b049b471d11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
